server:
  port: 8999

file:
  host: sh.hc-yun.com
  port: 6186
  username: Mango-jianchengfeng
  password: uc<5ay0U
  folder-path: /Demo/data
  # 类型选项可以是FTP或者SMB
  type: FTP
  # 登录类型选项：USER/GUEST
  login-type: USER
  server-encode: UTF-8
